In [35]:
import numpy as np

Arithmetic Operations

In [36]:
a1 = np.array ([1,2,3,4,5])

In [37]:
a2 = s1 = np.array ([6,7,8,9,10])

In [38]:
a1

array([1, 2, 3, 4, 5])

In [39]:
a2

array([ 6,  7,  8,  9, 10])

In [40]:
sumarr = a1+a2

In [41]:
subarr = a1-a2

In [42]:
mularr = a1*a2

In [43]:
divarr = a1/a2

In [44]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [45]:
a1//a2

array([0, 0, 0, 0, 0])

BROADCASTING

In [46]:
l = [10,20,30,40]

In [47]:
arr = np.array(l)

In [48]:
arr+10

array([20, 30, 40, 50])

In [49]:
arr2 = np.arange(1,26).reshape(5,5)

In [50]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [51]:
arr2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [52]:
arr2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [53]:
arr2*10

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250]])

DEEP AND SHALLOW COPY

In [54]:
a = np.arange(1,21)

In [55]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [56]:
slice = a[:5]

In [57]:
slice = slice*10

In [58]:
slice

array([10, 20, 30, 40, 50])

In [59]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [60]:
a[4:6]*10

array([50, 60])

In [61]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [62]:
b = a

In [63]:
b[0] = 99

In [64]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [66]:
c = a.copy()
#shallow copy

In [67]:
c[0] = 55

In [68]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

MATRIX OPERATIONS

In [69]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [70]:
A

array([[1, 2],
       [3, 4]])

In [71]:
B

array([[5, 6],
       [7, 8]])

In [72]:
A*B

array([[ 5, 12],
       [21, 32]])

In [73]:
A@B

array([[19, 22],
       [43, 50]])

In [74]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [75]:
A

array([[1, 2],
       [3, 4]])

ADVANCED ARRAY MANIPULATION

In [76]:
A

array([[1, 2],
       [3, 4]])

In [77]:
B

array([[5, 6],
       [7, 8]])

In [78]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [80]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [81]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [82]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

SPLITTING ARRAY

In [83]:
c = np.arange(16).reshape(4,4)

In [84]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [85]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [86]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]