In [32]:
import numpy as np 

NUMPY INDEXING AND SLICING OF VECTORS

In [33]:
arr = np.arange(11,21)

In [34]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [35]:
print(arr[6])

17


In [36]:
print(arr[9])

20


In [37]:
print(arr[1:5:1])

[12 13 14 15]


In [38]:
arrslice = arr[3::2]

NUMPY INDEXING AND SLICING OF MATRIX

In [39]:
arr = np.arange(1,31).reshape(6,5)

In [40]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [41]:
arr[0]

array([1, 2, 3, 4, 5])

In [42]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [43]:
 arr[0,0]

np.int64(1)

In [44]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [45]:
 arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [46]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

BOOLEAN INDEXING

In [47]:
arr = np.arange(11,21)

In [48]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [49]:
 bool_index = arr%2==0

In [50]:
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [51]:
arr = arr[bool_index]

In [52]:
arr

array([12, 14, 16, 18, 20])