In [32]:
!pip install numpy


Defaulting to user installation because normal site-packages is not writeable


In [33]:
import numpy as np


Basic Array Creation

In [34]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [35]:
print(arr)

[1 2 3 4]


DATATYPES

In [36]:
a = [1,2,3.5,6,"hello"]

In [37]:
np.array(a)

array(['1', '2', '3.5', '6', 'hello'], dtype='<U32')

In [38]:
b = [1,2,3.5,6]

In [39]:
np.array(b)

array([1. , 2. , 3.5, 6. ])

VECTORS AND MATRIX

In [40]:
l = [[1,2,3],[4,5,6],[7,8,9]]

In [41]:
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [42]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

ARRAY GENERATION FUNCTION

In [43]:
genarr1 = np.arange(1,11)

In [44]:
genarr2 = np.arange(1,11,2)

ZEROES 

In [45]:
zarr = np.zeros(6)

In [46]:
zarr

array([0., 0., 0., 0., 0., 0.])

In [47]:
zarr2 = np.zeros((6,6))

In [48]:
zarr2

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [49]:
onearr = np.ones((6,6))

In [50]:
onearr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [53]:
arrspaced = np.linspace (0,1,100)

In [54]:
arrspaced

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

RANDOM GENERATION FUNCTION

In [55]:
np.random.rand(5)

array([0.52960907, 0.29441338, 0.45958226, 0.84237933, 0.66020576])

In [56]:
np.random.rand(10)

array([0.11256941, 0.62152321, 0.83694652, 0.74837234, 0.63137422,
       0.30471649, 0.01197543, 0.41734902, 0.04887469, 0.19390898])

All values are there between 0 and 1.

Concept of normalization

In [59]:
np.random.rand(5)

array([0.01232728, 0.14990232, 0.36304067, 0.67119305, 0.04738312])

Numbers 0 ke aas-paas

In [62]:
np.random.randn(100)

array([ 0.03538609,  1.44795731,  1.82034378, -0.99958696, -1.90394904,
       -0.07048286, -0.89341234, -0.66240753, -1.29789653,  0.96087081,
       -0.91144787, -1.02667775,  0.95677953, -0.43778952, -0.29544064,
       -0.83688291, -0.53967184,  0.73474696,  0.58252369,  1.83134316,
       -1.43771079,  1.63767874, -0.30711181, -0.61089877,  0.46138463,
        0.52312014,  1.2866516 ,  0.99758704,  1.27182463, -1.66692468,
       -0.92974922, -0.6417578 ,  0.8757318 , -1.69035356,  0.39996195,
       -0.1809877 , -1.29613659, -0.2714021 , -1.45679742,  1.72830676,
       -1.10727819,  0.25705659, -0.02992567, -0.90968188,  1.56340131,
       -1.28934936,  0.66418848,  0.15236119, -0.53564273, -1.36617019,
       -0.54262669,  1.06130188, -1.67212185, -0.44843231, -0.15788358,
        0.10834191,  0.33555484, -1.12594493, -1.15141648, -0.68748729,
       -0.33870087,  0.81163979, -0.73698658,  0.2464505 ,  1.02607941,
        1.24367428, -1.07504218,  0.9020516 ,  0.32314338,  1.14