In [97]:
import numpy as np

**Valid Sudoku**

In [98]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [99]:
s.sum()

np.int64(405)

In [100]:
b = np.sum(s,axis = 1)
b==45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [101]:
c = np.sum(s,axis = 0)
c == 45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [102]:
b1 = s[0:3,0:3]
b1.sum()


np.int64(45)

In [103]:
b2 = s[0:3,3:6]
b2.sum()

np.int64(45)

In [104]:
b3 = s[0:3,6:9]
b3.sum()

np.int64(45)

In [105]:
for i in range(0,9,3):
    for j in range(0,9,3):
        print(s[i:i+3,j:j+3].sum())

45
45
45
45
45
45
45
45
45


**General Questions**

In [106]:


# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [107]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [108]:
#Find the average age of students.
data[:,0].mean()

np.float64(18.4)

In [109]:
#Extract Math marks of all students.
data[:,1]

array([85, 92, 76, 65, 90])

In [110]:
#Find the highest Science mark.
data[:,2].max()

np.int64(95)

In [111]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1]>90]


array([[19, 92, 88]])

In [112]:
#Increase Math marks of all students by 5.
data[:,1]+=5

In [113]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [114]:
#Find how many students are younger than 19.
(data[:,0]<19).sum()

np.int64(3)

In [115]:
#Calculate the average marks in each subject (column-wise mean).
marks = (data[:,1:])

In [116]:
np.mean(marks,axis=0)

array([86.6, 83.2])

In [117]:
marks.mean(axis=0)

array([86.6, 83.2])

In [118]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1]>=80) & (data[:,2]>=80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [119]:
#Replace all Science marks < 75 with 0.
data[:,2][(data[:,2]<75)] = 0

In [120]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])

In [121]:
data[data[:,2]<75,2] = 0

In [122]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])