In [468]:
import numpy as np

In [469]:
myarr = np.array([[1,2,3,4,37222]], np.int64)

In [470]:
myarr[0,1]

np.int64(2)

In [471]:
myarr.shape


(1, 5)

In [472]:
myarr.dtype

dtype('int64')

In [473]:
myarr[0,1] = 45

In [474]:
myarr

array([[    1,    45,     3,     4, 37222]])

In [475]:
myarr.dtype

dtype('int64')

**Array creation: Conversion from other python structures**

In [476]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [477]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [478]:
listarray.dtype

dtype('int64')

In [479]:
listarray.shape

(3, 3)

In [480]:
listarray.size

9

In [481]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [482]:
zeros = np.zeros((2,5))

In [483]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [484]:
zeros.dtype

dtype('float64')

In [485]:
zeros.shape

(2, 5)

In [486]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [487]:
l_space = np.linspace(1,100,50)

In [488]:
l_space

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [489]:
emp = np.empty((4,6))

In [490]:
emp

array([[4.67296746e-307, 1.69121096e-306, 1.11260280e-306,
        1.89146896e-307, 7.56571288e-307, 4.00544531e-307],
       [1.11261095e-306, 3.56043054e-307, 1.37961641e-306,
        2.22518251e-306, 1.33511969e-306, 6.23038336e-307],
       [9.34609790e-307, 8.45593934e-307, 9.34600963e-307,
        3.56036603e-307, 1.37961641e-306, 1.37961302e-306],
       [1.11259940e-306, 1.60219035e-306, 1.11261570e-306,
        1.06811354e-306, 8.34448533e-308, 2.22507386e-306]])

In [491]:
emp_like = np.empty_like(l_space)

In [492]:
emp_like

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [493]:
ide = np.identity(7)

In [494]:
ide

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [495]:
ide.shape

(7, 7)

In [496]:
arr = np.arange(99)

In [497]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [498]:
arr = arr.reshape(3,33)

In [499]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [500]:
arr = arr.ravel()

In [501]:
arr.shape

(99,)

In [502]:
 x = [[1,2,3],[4,5,6],[7,1,0]]

In [503]:
ar = np.array(x)

In [504]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [505]:
ar.sum(axis=0)

array([12,  8,  9])

In [506]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [507]:
ar = ar.T

In [508]:
ar

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [509]:
ar.flat

In [510]:
for item in ar.flat:
    print(item)

1
4
7
2
5
1
3
6
0


In [511]:
ar.ndim

2

In [512]:
ar.size

9

In [513]:
ar.nbytes

72

In [514]:
one = np.array([1,3,4,634,2])

In [515]:
one.argmax()

np.int64(3)

In [516]:
one.argmin()

np.int64(0)

In [517]:
one.argsort()

array([0, 4, 1, 2, 3])

In [518]:
ar

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [519]:
ar.argmin()

np.int64(8)

In [520]:
ar.argmax()

np.int64(2)

In [521]:
ar.argmax(axis=0)

array([2, 2, 0])

In [522]:
ar.argmax(axis=1)

array([2, 1, 1])

In [523]:
ar.ravel()


array([1, 4, 7, 2, 5, 1, 3, 6, 0])

In [524]:
ar.reshape(9,1)

array([[1],
       [4],
       [7],
       [2],
       [5],
       [1],
       [3],
       [6],
       [0]])

In [525]:
ar2 = np.array([[1,2,1],
                [4,0,6],
                [7,1,0]])

In [526]:
ar+ar2

array([[ 2,  6,  8],
       [ 6,  5,  7],
       [10,  7,  0]])

In [527]:
[324,34]+[34,546]

[324, 34, 34, 546]

In [528]:
ar*ar2

array([[ 1,  8,  7],
       [ 8,  0,  6],
       [21,  6,  0]])

In [529]:
np.sqrt(ar2)

array([[1.        , 1.41421356, 1.        ],
       [2.        , 0.        , 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [530]:
 ar2.sum()

np.int64(22)

In [531]:
ar2.max()

np.int64(7)

In [532]:
ar2.min()

np.int64(0)

In [534]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [7, 1, 0]])

In [535]:
np.where(ar2>2)

(array([1, 1, 2]), array([0, 2, 0]))

In [536]:
type(np.where(ar2>2))

tuple

In [537]:
np.count_nonzero(ar2)

np.int64(7)

In [538]:
ar2[1,2]=0

In [539]:
np.count_nonzero(ar2)

np.int64(6)

In [540]:
np.nonzero(ar2)

(array([0, 0, 0, 1, 2, 2]), array([0, 1, 2, 0, 0, 1]))

**numpy arrays take less space as compared to python arrays**

In [541]:
import sys

In [543]:
py_ar = [0,4,55,2]

In [544]:
np_ar = np.array(py_ar)

In [548]:
sys.getsizeof(1)

28

In [547]:
sys.getsizeof(1)*len(py_ar)

112

In [550]:
np_ar.itemsize

8

In [551]:
np_ar.size

4

In [549]:
np_ar.itemsize*np_ar.size

32

In [552]:
np_ar.tolist()

[0, 4, 55, 2]